### PR TITLE
[adaptive_breakpoints] Refactoring

### PR DESCRIPTION
**Pull request by Ascenio**
- Swaps the use of enums, extensions and map for a simpler class. 
- Adds some comments to public API.

> Doesn't represent a **breaking change**.
> Tests are passing as previously.

### CODE REVIEW

**Comment by guidezpl** [comment]
cc @JoseAlba

**Comment by clocksmith** [comment]
Hi thank you for helping out! This looks good! One concern in terms of it being a breaking change is that with the change from enum to class, but the AdaptiveWindowType can no longer be used in switch statements.

It might be good to make this change even it's breaking (and upping the major version number), because comparison checks for window type can still be made on the class even without a switch statement, with the the >, <, and == operator.

 @JoseAlba what do you think?

**Comment by Ascenio** [comment]
That's true, switch statements are not possible anymore, but, as switch are generally discouraged, and as in this case there are lots of attributes associated which each one, I think it's a good price to pay.

**Review by JoseAlba — APPROVED** [review]
LGTM can you please update the pubspec.yaml file from 0.0.5 to 0.1.0 because it is a breaking change.

**Comment by clocksmith** [comment]
and CHANGELOG

**Comment by Ascenio** [comment]
Done. What do you guys think?

**Comment by clocksmith** [comment]
published, thanks!

**Pull request merged**
