### PR TITLE
Allow NavigationRailLabelType to be specified for labels in the navigation rail

### PR DESCRIPTION
**Pull request by dsyrstad**
Support labels as shown in https://material.io/components/navigation-rail#behavior. Also supports tooltips in rail mode to match behavior of `BottomNavigationBar`. Also handle selectedIndex overflow on BottomNavigationBar and NavigationRail.

### CODE REVIEW

**Comment by guidezpl** [comment]
Since this is a material component, we have to adhere to the Material specs. Thus, I can't accept this contribution as-is, though I suggest sharing component with the community as a package (if it doesn't exist already).

**Comment by guidezpl** [comment]
Thank you for your contribution. I'm going to close this PR for now since we're moving this package. Please don't hesitate to submit a new PR at https://github.com/material-foundation/flutter-packages if you have the time. Thanks!

**Comment by dsyrstad** [comment]
@guidezpl Sad. This PR just sat there. I've long since forked it and I'm using my own version.

**Comment by guidezpl** [comment]
Apologies, this repo fell under the radar until now. Once I move the package, a contribution would be welcome.

**Pull request closed without merging**
